---
- name: Update apt-get
  apt: update_cache=yes
  become: yes

- name: Upgrade apt-get
  action: apt upgrade=dist
  become: yes

- name: Install essential packages
  apt: name={{item}} state=installed
  become: yes
  with_items:
      - build-essential
      - git
      - vim
      - language-pack-es-base
      - libtiff5-dev
      - libjpeg8-dev 
      - zlib1g-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libwebp-dev
      - tcl8.6-dev

- name: Install python3 related packages
  apt: name={{item}} state=installed
  become: yes
  with_items:
      - python3-software-properties
      - python3-dev
      - python3-setuptools
      - python3-pip
      - python-psycopg2

- name: upgrade pip3
  become: yes
  command: pip3 install --upgrade pip

- name: Set HOSTNAME
  become: yes
  hostname: name={{inventory_hostname}}