---
- name: Update apt-get
  apt: update_cache=yes
  become: yes

- name: Upgrade apt-get
  action: apt upgrade=dist
  become: yes

- name: Install postgres
  apt: name={{item}} state=installed
  become: yes
  with_items:
      - libpq-dev
      - postgresql-9.5
      - postgresql-client-9.5
      - postgresql-server-dev-9.5
      - python3-psycopg2

- name: setup database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{db_name}}"
    state: present

- name: setup database user
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{db_name}}"
    name: "{{db_user}}"
    password: "{{db_pass}}"
    role_attr_flags: CREATEDB
    state: present

- name: grant privileges to user
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{db_name}}"
    privs: ALL
    type: database
    role: "{{db_user}}"